name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev
      - name: Create Build Directory
        run: mkdir build && cd build
      - name: Run CMake
        run: cmake ..
      - name: Build
        run: cmake --build .
