name: C++ CI

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install SDL2
        run: sudo apt-get install libsdl2-dev
      - name: Compiling
        run: make
